<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.apache.netbeans.cnd</groupId>
        <artifactId>cnd-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>cnd-makeproject</artifactId>
    <packaging>nbm</packaging>
    <name>CND — Make Project</name>

    <build>
        <sourceDirectory>src</sourceDirectory>
        <testSourceDirectory>test/unit/src</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <cluster>cnd</cluster>
                    <moduleName>org.netbeans.modules.cnd.makeproject</moduleName>
                    <sourceManifestFile>manifest.mf</sourceManifestFile>
                    <publicPackages>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api.configurations</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api.launchers</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api.runprofiles</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api.support</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.api.wizards</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.spi</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.spi.configurations</publicPackage>
                        <publicPackage>org.netbeans.modules.cnd.makeproject.uiapi</publicPackage>
                    </publicPackages>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>cnd-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>cnd-api-project</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>cnd-api-remote</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>cnd-toolchain</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>cnd-utils</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>dlight-libs-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.netbeans.cnd</groupId>
            <artifactId>dlight-remote</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-annotations-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-java-classpath</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-progress</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-extexecution</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-parsing-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-parsing-indexing</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-projectapi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-projectuiapi-base</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-queries</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-filesystems</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-modules</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-lookup</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules</groupId>
            <artifactId>org-netbeans-modules-dlight-nativeexecution</artifactId>
        </dependency>
        <dependency>
            <groupId>org.netbeans.modules</groupId>
            <artifactId>org-netbeans-modules-dlight-terminal</artifactId>
        </dependency>
    </dependencies>
</project>
